import os
import time
import subprocess

print("Qwen 7B (Layer 17) run is already finished. Starting master batch execution...")

# 2. Define the tasks
scripts_all = [
    "02_extract_refusal_direction.py",
    "03_verify_direction.py",
    "04_orthogonalize_model.py",
    "05_stage1_generation.py",
    "06_stage2_harm_recognition.py",
    "06b_confusion_matrix_eval.py",
    "07_activation_analysis.py",
    "08_attention_head_analysis.py",
    "09_generate_plots.py"
]

scripts_controls = [
    "10_run_controls.py",
    "11_paraphrase_prompts.py",
    "12_external_harm.py",
    "13_ablation_verification.py",
    "14_save_activation_samples.py",
    "16_generate_missing_figures.py",
    "15_format_final_paper.py"
]

models = [
    {
        "name": "qwen14b",
        "model_id": "Qwen/Qwen1.5-14B-Chat",
        "results_dir": "qwen14b_results",
        "ablated_dir": "qwen14b_ablated",
        "layer": 23,
        "scripts": scripts_all + scripts_controls
    }
]

config_path = r"C:\Users\USER\Desktop\Urja\Q1_final\cognitive_dissociation\scripts\config.py"

def write_config(m):
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(f'''import os

# --- DYNAMIC CONFIG GENERATED BY MASTER BATCH ---
CURRENT_RUN = "{m['name']}"
MODEL_ID = "{m['model_id']}"
RESULTS_DIR_NAME = "{m['results_dir']}"
ABLATED_MODEL_DIR_NAME = "{m['ablated_dir']}"
DEFAULT_LAYER = {m['layer']}

# Helper paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR = os.path.join(BASE_DIR, RESULTS_DIR_NAME)

def get_results_dir():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    return RESULTS_DIR

def get_ablated_model_dir():
    return os.path.join(BASE_DIR, "models", ABLATED_MODEL_DIR_NAME)
''')

base_wd = r"C:\Users\USER\Desktop\Urja\Q1_final\cognitive_dissociation"

for m in models:
    print(f"\n{'='*50}\nStarting pipeline for {m['name']}\n{'='*50}")
    write_config(m)
    for script in m["scripts"]:
        script_path = os.path.join(base_wd, "scripts", script)
        print(f"[{m['name']}] Running {script}...")
        try:
            subprocess.run(["python", script_path], cwd=base_wd, check=True)
        except subprocess.CalledProcessError as e:
            print(f"ERROR running {script} for {m['name']}. Continuing...")
            # We continue so that a failure in one model doesn't halt the entire 12 hour batch
            pass

print("\nMASTER BATCH EXECUTION COMPLETE!")
