import os

# --- DYNAMIC CONFIG GENERATED BY MASTER BATCH M2 ---
CURRENT_RUN = "llama3_8b"
MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
RESULTS_DIR_NAME = "llama_results_layer11"
ABLATED_MODEL_DIR_NAME = "llama3_8b_ablated_layer11"
DEFAULT_LAYER = 11

# Generation controls
DO_SAMPLE = True
TEMPERATURE = 1.0
# Hardware limits (A100=128, RTX 3090/Quadro=32)
BATCH_SIZE = 8

# Helper paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR_NAME = os.environ.get("RESULTS_DIR", RESULTS_DIR_NAME)
RESULTS_DIR = os.path.join(BASE_DIR, RESULTS_DIR_NAME)

ABLATED_MODEL_DIR_NAME = os.environ.get("ABLATED_MODEL_DIR_NAME", ABLATED_MODEL_DIR_NAME)

def get_results_dir():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    return RESULTS_DIR

def get_ablated_model_dir():
    return os.path.join(BASE_DIR, "models", ABLATED_MODEL_DIR_NAME)
