import os

# --- DYNAMIC CONFIG GENERATED BY MASTER BATCH M2 ---
CURRENT_RUN = "llama3_8b"
MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
RESULTS_DIR_NAME = "llama_results_620_t06"
ABLATED_MODEL_DIR_NAME = "llama3_8b_ablated_620"
DEFAULT_LAYER = 12

# Generation controls
# Generation controls
DO_SAMPLE = True
TEMPERATURE = 0.6

# Helper paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR_NAME = os.environ.get("RESULTS_DIR", RESULTS_DIR_NAME)
RESULTS_DIR = os.path.join(BASE_DIR, RESULTS_DIR_NAME)

def get_results_dir():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    return RESULTS_DIR

def get_ablated_model_dir():
    return os.path.join(BASE_DIR, "models", ABLATED_MODEL_DIR_NAME)
